name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: macos-latest
    # have to convert to container to install glibcxx
    # container:
    #   image: node:20
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      # install glibcxx as isolated vm depends on it
      # - name: Install Dependencies for GLIBCXX
      #   run: |
      #     apt-get update && \
      #     apt-get install -y build-essential libstdc++6

      - name: Print GLIBCXX Version
        run: strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX

      - name: Set LD_LIBRARY_PATH
        run: |
          echo "export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Install Project Dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
